### ISSUE TITLE
Resizing time-stamped event to another day

### ISSUE THREAD

**Issue by NeoMatrixafk** [ayush-sharma11/calendara#31]
In timeGrid view, when an existing 1 day event with time stamp, is resized to another day or across multiple days, backend isnt accepting it.
No errors being thrown, also alert "Event updated successfully" is popping.
![issue](https://github.com/ayush-sharma11/calendara/assets/125139752/a56e661a-f0c9-40dc-82ce-4ff6e79e86ac)

**Comment by ayush-sharma11** [comment]
> In timeGrid view, when an existing 1 day event with time stamp, is resized to another day or across multiple days, backend isnt accepting it. No errors being thrown, also alert "Event updated successfully" is popping. ![issue](https://private-user-images.githubusercontent.com/125139752/313639932-a56e661a-f0c9-40dc-82ce-4ff6e79e86ac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk4MzgsIm5iZiI6MTcxMDc1OTUzOCwicGF0aCI6Ii8xMjUxMzk3NTIvMzEzNjM5OTMyLWE1NmU2NjFhLWYwYzktNDBkYy04MmNlLTRmZjZlNzllODZhYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY2MWYzOGQ4NTZmMzE3Yjg5MWRhZjc3ZmI4ZTY4NjIxOTM4ZDVlZjQyZTllN2M1ZTI1OTRhZmE3NzBjOGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l_cb4kOxpGrv-19YxbFAkb60Ip5ZM5LRgGfZ1XpmKuU) [ ![issue](https://private-user-images.githubusercontent.com/125139752/313639932-a56e661a-f0c9-40dc-82ce-4ff6e79e86ac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk4MzgsIm5iZiI6MTcxMDc1OTUzOCwicGF0aCI6Ii8xMjUxMzk3NTIvMzEzNjM5OTMyLWE1NmU2NjFhLWYwYzktNDBkYy04MmNlLTRmZjZlNzllODZhYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY2MWYzOGQ4NTZmMzE3Yjg5MWRhZjc3ZmI4ZTY4NjIxOTM4ZDVlZjQyZTllN2M1ZTI1OTRhZmE3NzBjOGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l_cb4kOxpGrv-19YxbFAkb60Ip5ZM5LRgGfZ1XpmKuU) ](https://private-user-images.githubusercontent.com/125139752/313639932-a56e661a-f0c9-40dc-82ce-4ff6e79e86ac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk4MzgsIm5iZiI6MTcxMDc1OTUzOCwicGF0aCI6Ii8xMjUxMzk3NTIvMzEzNjM5OTMyLWE1NmU2NjFhLWYwYzktNDBkYy04MmNlLTRmZjZlNzllODZhYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY2MWYzOGQ4NTZmMzE3Yjg5MWRhZjc3ZmI4ZTY4NjIxOTM4ZDVlZjQyZTllN2M1ZTI1OTRhZmE3NzBjOGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l_cb4kOxpGrv-19YxbFAkb60Ip5ZM5LRgGfZ1XpmKuU) [ ](https://private-user-images.githubusercontent.com/125139752/313639932-a56e661a-f0c9-40dc-82ce-4ff6e79e86ac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk4MzgsIm5iZiI6MTcxMDc1OTUzOCwicGF0aCI6Ii8xMjUxMzk3NTIvMzEzNjM5OTMyLWE1NmU2NjFhLWYwYzktNDBkYy04MmNlLTRmZjZlNzllODZhYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY2MWYzOGQ4NTZmMzE3Yjg5MWRhZjc3ZmI4ZTY4NjIxOTM4ZDVlZjQyZTllN2M1ZTI1OTRhZmE3NzBjOGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l_cb4kOxpGrv-19YxbFAkb60Ip5ZM5LRgGfZ1XpmKuU)

will check it out

**Comment by ayush-sharma11** [comment]
will check it out

**Comment by NeoMatrixafk** [comment]
In google calendar, it blocks single day event with time stamp to be resized to next day.
So, did the same.

![fix](https://github.com/ayush-sharma11/calendara/assets/125139752/5dabde22-5767-428c-89a1-2d2eb344be82)

**Comment by NeoMatrixafk** [comment]
In google calendar, it blocks a singe day event with time stamp to be resized to another day(s).
So, implemented that logic here as well.

![fix](https://github.com/ayush-sharma11/calendara/assets/125139752/b538ddd3-c74e-4018-a651-886e1ee37c81)
